### ISSUE TITLE
No Query results

### ISSUE THREAD

**Issue by brandenwagner** [kirschbaum/laravel-spark-pages#4]
No query results for model [Kirschbaum\LaravelSparkPages\Page].

This happens, after initial install before i can even add a page

**Comment by kirschbaum** [comment]
Hey @brandenwagner,

Thanks for reaching out. Happy to help. What are you trying to do when this happens? Are you trying to visit a particular page? Were you able to get through all the installation instructions without issue?

**Comment by brandenwagner** [comment]
I followed all of the instructions, and then when i run the server and
attempted to visit the landing page i recieved that error.

_Branden Wagner_
PureIntellect.Com
branden@pureintellect.com
http://www.pureintellect.com/

On Wed, Oct 19, 2016 at 3:41 PM, Nathan Kirschbaum <notifications@github.com

**Comment by fwartner** [comment]
Having the same problems..

**Comment by marktopper** [comment]
[The problem](https://github.com/kirschbaum/laravel-spark-pages/blob/master/src/routes.php#L11) is that all pages are catched.

Instead of only the once added as a page.

**EDIT**: My recommendation would be to check the database and make a route for that.

**Comment by sairamc** [comment]
Encountered similar error when editing the existing pages. It is because of the slug that's in the database has a leading "/" character. Which is making the edit page not accessible from the routes. If you delete the leading "/" character in the database from slug field, you could goto edit page, but it will prevent from going to the actual page which is being published. 

Adding the following line to the edit method in PageController fixed the issue
$slug = $this->formatSlugForQuery($slug, null);

**Comment by kirschbaum** [comment]
@luisdalmolin can you take a look at this PR when you have a few minutes. Would like to get this merged in if all is well. 

Apologies for the delay in reviewing this PR folks.
